name: Monthly Data Fetch

on:
  schedule:
    # Runs at midnight UTC on the 3rd of every month
    - cron: '0 0 3 * *'
  workflow_dispatch:  # enables manual triggering

jobs:
  fetch_and_process:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'  # Choose the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Ensure you have a requirements.txt file with your dependencies

    - name: Run the script
      run: |
        python ranking.py  # Make sure this matches your script filename

    - name: Create a new release
      uses: softprops/action-gh-release@v2.0.8
      with:
        files: mutual_funds_ranking_*.xlsx
