name: Monthly Data Fetch

on:
  schedule:
    # Runs at midnight UTC on the 3rd of every month
    - cron: '0 0 3 * *'
  workflow_dispatch:  # enables manual triggering

jobs:
  fetch_and_process:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.7

    - name: Set up Python
      uses: actions/setup-python@v5.1.1
      with:
        python-version: '3.9'  # Choose the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Ensure you have a requirements.txt file with your dependencies

    - name: Run the script
      run: |
        python ranking.py  # Make sure this matches your script filename
    
    - name: Create Release Tag
      id: tag
      run: |
        tag_name=v0.0.${{ github.run_number }}
        git tag -a $tag_name -m "Automated tag for release $tag_name"
        git push origin $tag_name
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create a new release
      uses: softprops/action-gh-release@v2.0.8
      with:
        files: mutual_funds_ranking_*.xlsx
        tag_name: ${{ steps.tag.outputs.tag_name }}
        release_name: "Automated release v0.0.${{ github.run_number }}"
        make_latest: true
